import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Outfit, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Toolbar from "@/components/Toolbar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${robotoMono.variable} dark`}>
      <body
        className="antialiased"
      >
        <Toolbar />
        {children}
      </body>
    </html>
  );
}
